#!/usr/bin/env python3
import os
import sys


def embed_assets(input_files, output_header, output_cc, namespace="mujoco", variable_name="filament_assets_embed"):
   files = []
   for path in input_files:
       if not os.path.isfile(path):
           continue
       rel_path = os.path.basename(path)
       files.append((rel_path, path))


   with open(output_header, "w") as f:
       f.write("// Autogenerated by embed_assets.py\n")
       f.write("#pragma once\n")
       f.write("#include <cstddef>\n")
       f.write("#include <cstdint>\n\n")
       f.write(f"namespace {namespace} {{\n\n")
       f.write("struct FileToc {\n")
       f.write("  const char* name;\n")
       f.write("  const uint8_t* data;\n")
       f.write("  size_t size;\n")
       f.write("};\n\n")
       f.write(f"const FileToc* {variable_name}_create();\n")
       f.write(f"size_t {variable_name}_size();\n\n")
       f.write(f"}}  // namespace {namespace}\n")


   with open(output_cc, "w") as f:
       f.write("// Autogenerated by embed_assets.py\n")
       f.write(f'#include "{os.path.basename(output_header)}"\n\n')
       f.write(f"namespace {namespace} {{\n\n")


       for i, (rel_path, full_path) in enumerate(files):
           var_name = f"data_{i}"
           f.write(f"const uint8_t {var_name}[] = {{\n")
           with open(full_path, "rb") as bf:
               data = bf.read()
               for j in range(0, len(data), 12):
                   chunk = data[j:j+12]
                   f.write("  " + ", ".join(f"0x{b:02x}" for b in chunk) + ",\n")
           f.write("};\n\n")


       f.write(f"const FileToc {variable_name}_toc[] = {{\n")
       for i, (rel_path, _) in enumerate(files):
           with open(files[i][1], "rb") as bf:
               size = len(bf.read())
           f.write(f'  {{"{rel_path}", data_{i}, {size}}},\n')
       f.write("};\n\n")


       f.write(f"const FileToc* {variable_name}_create() {{\n")
       f.write(f"  return {variable_name}_toc;\n")
       f.write("}\n\n")


       f.write(f"size_t {variable_name}_size() {{\n")
       f.write(f"  return {len(files)};\n")
       f.write("}\n\n")
       f.write(f"}}  // namespace {namespace}\n")


if __name__ == "__main__":
   if len(sys.argv) < 4:
       print("Usage: embed_assets.py <output_header> <output_cc> <input_file1> [input_file2 ...]")
       sys.exit(1)
   embed_assets(sys.argv[3:], sys.argv[1], sys.argv[2])
