package(default_visibility = ["//third_party/mujoco/wasm:__subpackages__"])

exports_files(
    srcs = glob(["*"]),
    visibility = ["//third_party/mujoco/wasm/codegen:__subpackages__"],
)

filegroup(
    name = "template_files",
    srcs = glob(["*"]),
)
