#ifndef MUJOCO_SRC_PLUGIN_PLASTICITY_J2_H_
#define MUJOCO_SRC_PLUGIN_PLASTICITY_J2_H_

#include <array>
#include <optional>
#include <vector>

#include <mujoco/mjdata.h>
#include <mujoco/mjmodel.h>
#include <mujoco/mjtype.h>

namespace mujoco::plugin::plasticity {

namespace internal {

constexpr int kNumTetVertices = 4;
constexpr int kNumTetEdges = 6;
constexpr int kSpatialDimension = 3;


// -----------------------------------------------------------------------------
// Reference-space data for one tetrahedral element.
// -----------------------------------------------------------------------------

struct ElementReference {
  std::array<mjtNum, 9> inv_dm;

  mjtNum volume;

  // MuJoCo tetrahedral edge ordering:
  //
  //   0 : (0, 1)
  //   1 : (1, 2)
  //   2 : (2, 0)
  //   3 : (2, 3)
  //   4 : (0, 3)
  //   5 : (1, 3)
  //
  std::array<std::array<mjtNum, 3>, kNumTetEdges> reference_edges;

  // Full row-major 6x6 edge stiffness matrix.
  std::array<mjtNum, kNumTetEdges * kNumTetEdges> stiffness;

  // Shear modulus reconstructed from native flex stiffness.
  mjtNum shear_modulus;
};


// -----------------------------------------------------------------------------
// Current element kinematics.
// -----------------------------------------------------------------------------

struct ElementKinematics {
  // F = Ds Dm^-1
  std::array<mjtNum, 9> deformation_gradient;

  // E = 1/2 (F^T F - I)
  std::array<mjtNum, 9> green_strain;

  // J = det(F)
  mjtNum jacobian;
};


// -----------------------------------------------------------------------------
// Elastic J2 trial state.
// -----------------------------------------------------------------------------

struct TrialState {
  // E_trial^e = E - E^p
  std::array<mjtNum, 9> elastic_strain;

  // s_trial = 2 G dev(E_trial^e)
  std::array<mjtNum, 9> deviatoric_stress;

  // sigma_eq = sqrt(3/2 s:s)
  mjtNum equivalent_stress;
};


// -----------------------------------------------------------------------------
// Perfect-plastic J2 return mapping result.
// -----------------------------------------------------------------------------

struct RadialReturnResult {
  // E_p[n+1], stored as:
  //
  //   [xx, yy, zz, xy, xz, yz]
  //
  std::array<mjtNum, 6> plastic_strain;

  std::array<mjtNum, 9> deviatoric_stress;

  mjtNum equivalent_stress;

  mjtNum plastic_multiplier;

  bool yielded;
};


// =============================================================================
// Pure mathematical helpers.
// =============================================================================

// Compute:
//
//   F = Ds Dm^-1
//   J = det(F)
//   E = 1/2 (F^T F - I)
//
ElementKinematics ComputeKinematics(const mjtNum ds[9], const mjtNum inv_dm[9]);


// Convert a symmetric tensor D into MuJoCo's six native edge coordinates:
//
//   q_i = 2 A_i^T D A_i
//
std::array<mjtNum, kNumTetEdges> TensorToEdgeCoordinates(
    const std::array<std::array<mjtNum, 3>, kNumTetEdges>& reference_edges,
    const mjtNum tensor[9]);


// Compute:
//
//   q^T K q
//
mjtNum EdgeQuadraticForm(
    const std::array<mjtNum, kNumTetEdges>& q,
    const std::array<mjtNum, kNumTetEdges * kNumTetEdges>& stiffness);


// Recover the native shear modulus from MuJoCo's edge stiffness matrix.
mjtNum ExtractShearModulus(const ElementReference& reference);


// Compute:
//
//   E_trial^e = E - E^p
//   s_trial   = 2 G dev(E_trial^e)
//   sigma_eq  = sqrt(3/2 s_trial:s_trial)
//
TrialState ComputeTrialState(const std::array<mjtNum, 9>& green_strain,
                             const mjtNum plastic_strain[6],
                             mjtNum shear_modulus);


// Perfect-plastic J2 radial return.
RadialReturnResult ComputeRadialReturn(const TrialState& trial,
                                       const mjtNum plastic_strain[6],
                                       mjtNum shear_modulus,
                                       mjtNum yield_stress);


// -----------------------------------------------------------------------------
// Plastic force correction.
// -----------------------------------------------------------------------------

// Compute the twelve Cartesian vertex-force components generated by the
// plastic strain correction for one tetrahedron.
//
// current_positions is:
//
//   [x0, y0, z0,
//    x1, y1, z1,
//    x2, y2, z2,
//    x3, y3, z3]
//
// Plastic strain is stored as:
//
//   [xx, yy, zz, xy, xz, yz]
//
// The correction is:
//
//   q_p,i = 2 A_i^T E_p A_i
//
//   r_p = K q_p
//
// followed by the same current-configuration edge gradients used by
// MuJoCo's native tetrahedral elasticity, but with the opposite sign:
//
//   f_correction = + G_x^T r_p
//
// so that:
//
//   f_native(q) + f_correction(q_p)
//
// is equivalent to the native elastic response evaluated at:
//
//   q_e = q - q_p.
//
std::array<mjtNum, kNumTetVertices * kSpatialDimension>
ComputePlasticVertexForces(
    const ElementReference& reference,
    const std::array<mjtNum, kNumTetVertices * kSpatialDimension>&
        current_positions,
    const mjtNum plastic_strain[6]);


// =============================================================================
// MuJoCo-backed tetrahedral helpers.
// =============================================================================

ElementReference BuildElementReference(const mjModel* m, int flex_id,
                                       int element);


ElementKinematics ComputeElementKinematics(const mjModel* m, const mjData* d,
                                           int flex_id, int element,
                                           const ElementReference& reference);

}  // namespace internal


// =============================================================================
// J2 plasticity plugin.
// =============================================================================

class J2 {
 public:
  static std::optional<J2> Create(const mjModel* m, mjData* d, int instance);

  J2(J2&&) = default;
  J2(const J2&) = delete;
  J2& operator=(const J2&) = delete;
  ~J2() = default;

  void Compute(const mjModel* m, mjData* d, int instance);

  void Advance(const mjModel* m, mjData* d, int instance);

  void Reset(mjtNum* plugin_state);

  static void RegisterPlugin();

 private:
  J2(const mjModel* m, int flex_id, int element_count, mjtNum yield_stress);

  internal::ElementKinematics ComputeElementKinematics(const mjModel* m,
                                                       const mjData* d,
                                                       int element) const;

  int flex_id_;
  int element_count_;

  // J2 yield stress sigma_y.
  mjtNum yield_stress_;

  // Immutable data, one record per tetrahedron.
  std::vector<internal::ElementReference> reference_;

  // Candidate E_p[n+1] generated during Compute() and committed only
  // by Advance().
  std::vector<std::array<mjtNum, 6>> pending_plastic_strain_;
};

}  // namespace mujoco::plugin::plasticity

#endif  // MUJOCO_SRC_PLUGIN_PLASTICITY_J2_H_