// Copyright 2025 DeepMind Technologies Limited
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// DO NOT EDIT. THIS FILE IS AUTOMATICALLY GENERATED.

#include <mujoco/experimental/usd/mjcPhysics/bodyAPI.h>

#include <pxr/usd/sdf/assetPath.h>
#include <pxr/usd/sdf/types.h>
#include <pxr/usd/usd/schemaRegistry.h>
#include <pxr/usd/usd/typed.h>

PXR_NAMESPACE_OPEN_SCOPE

// Register the schema with the TfType system.
TF_REGISTRY_FUNCTION(TfType) {
  TfType::Define<MjcPhysicsBodyAPI, TfType::Bases<UsdAPISchemaBase> >();
}

/* virtual */
MjcPhysicsBodyAPI::~MjcPhysicsBodyAPI() {}

/* static */
MjcPhysicsBodyAPI MjcPhysicsBodyAPI::Get(const UsdStagePtr& stage,
                                         const SdfPath& path) {
  if (!stage) {
    TF_CODING_ERROR("Invalid stage");
    return MjcPhysicsBodyAPI();
  }
  return MjcPhysicsBodyAPI(stage->GetPrimAtPath(path));
}

/* virtual */
UsdSchemaKind MjcPhysicsBodyAPI::_GetSchemaKind() const {
  return MjcPhysicsBodyAPI::schemaKind;
}

/* static */
bool MjcPhysicsBodyAPI::CanApply(const UsdPrim& prim, std::string* whyNot) {
  return prim.CanApplyAPI<MjcPhysicsBodyAPI>(whyNot);
}

/* static */
MjcPhysicsBodyAPI MjcPhysicsBodyAPI::Apply(const UsdPrim& prim) {
  if (prim.ApplyAPI<MjcPhysicsBodyAPI>()) {
    return MjcPhysicsBodyAPI(prim);
  }
  return MjcPhysicsBodyAPI();
}

/* static */
const TfType& MjcPhysicsBodyAPI::_GetStaticTfType() {
  static TfType tfType = TfType::Find<MjcPhysicsBodyAPI>();
  return tfType;
}

/* static */
bool MjcPhysicsBodyAPI::_IsTypedSchema() {
  static bool isTyped = _GetStaticTfType().IsA<UsdTyped>();
  return isTyped;
}

/* virtual */
const TfType& MjcPhysicsBodyAPI::_GetTfType() const {
  return _GetStaticTfType();
}

UsdAttribute MjcPhysicsBodyAPI::GetSleepAttr() const {
  return GetPrim().GetAttribute(MjcPhysicsTokens->mjcSleep);
}

UsdAttribute MjcPhysicsBodyAPI::CreateSleepAttr(VtValue const& defaultValue,
                                                bool writeSparsely) const {
  return UsdSchemaBase::_CreateAttr(
      MjcPhysicsTokens->mjcSleep, SdfValueTypeNames->Token,
      /* custom = */ false, SdfVariabilityUniform, defaultValue, writeSparsely);
}

UsdAttribute MjcPhysicsBodyAPI::GetGravCompAttr() const {
  return GetPrim().GetAttribute(MjcPhysicsTokens->mjcGravcomp);
}

UsdAttribute MjcPhysicsBodyAPI::CreateGravCompAttr(VtValue const& defaultValue,
                                                    bool writeSparsely) const {
  return UsdSchemaBase::_CreateAttr(
      MjcPhysicsTokens->mjcGravcomp, SdfValueTypeNames->Double,
      /* custom = */ false, SdfVariabilityUniform, defaultValue, writeSparsely);
}

namespace {
static inline TfTokenVector _ConcatenateAttributeNames(
    const TfTokenVector& left, const TfTokenVector& right) {
  TfTokenVector result;
  result.reserve(left.size() + right.size());
  result.insert(result.end(), left.begin(), left.end());
  result.insert(result.end(), right.begin(), right.end());
  return result;
}
}  // namespace

/*static*/
const TfTokenVector& MjcPhysicsBodyAPI::GetSchemaAttributeNames(
    bool includeInherited) {
  static TfTokenVector localNames = {
      MjcPhysicsTokens->mjcSleep,
      MjcPhysicsTokens->mjcGravcomp,
  };
  static TfTokenVector allNames = _ConcatenateAttributeNames(
      UsdAPISchemaBase::GetSchemaAttributeNames(true), localNames);

  if (includeInherited)
    return allNames;
  else
    return localNames;
}

PXR_NAMESPACE_CLOSE_SCOPE
