// Copyright 2025 DeepMind Technologies Limited
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#include "./tokens.h"

PXR_NAMESPACE_OPEN_SCOPE

MjcPhysicsTokensType::MjcPhysicsTokensType()
    : affine("affine", TfToken::Immortal),
      auto_("auto", TfToken::Immortal),
      cg("cg", TfToken::Immortal),
      convex("convex", TfToken::Immortal),
      dense("dense", TfToken::Immortal),
      elliptic("elliptic", TfToken::Immortal),
      euler("euler", TfToken::Immortal),
      exact("exact", TfToken::Immortal),
      false_("false", TfToken::Immortal),
      filter("filter", TfToken::Immortal),
      filterexact("filterexact", TfToken::Immortal),
      fixed("fixed", TfToken::Immortal),
      implicit("implicit", TfToken::Immortal),
      implicitfast("implicitfast", TfToken::Immortal),
      integrator("integrator", TfToken::Immortal),
      legacy("legacy", TfToken::Immortal),
      mjcActDim("mjc:actDim", TfToken::Immortal),
      mjcActEarly("mjc:actEarly", TfToken::Immortal),
      mjcActLimited("mjc:actLimited", TfToken::Immortal),
      mjcActRangeMax("mjc:actRange:max", TfToken::Immortal),
      mjcActRangeMin("mjc:actRange:min", TfToken::Immortal),
      mjcBiasPrm("mjc:biasPrm", TfToken::Immortal),
      mjcBiasType("mjc:biasType", TfToken::Immortal),
      mjcCrankLength("mjc:crankLength", TfToken::Immortal),
      mjcCrankSite("mjc:crankSite", TfToken::Immortal),
      mjcCtrlLimited("mjc:ctrlLimited", TfToken::Immortal),
      mjcCtrlRangeMax("mjc:ctrlRange:max", TfToken::Immortal),
      mjcCtrlRangeMin("mjc:ctrlRange:min", TfToken::Immortal),
      mjcDynPrm("mjc:dynPrm", TfToken::Immortal),
      mjcDynType("mjc:dynType", TfToken::Immortal),
      mjcFlagActuation("mjc:flag:actuation", TfToken::Immortal),
      mjcFlagAutoreset("mjc:flag:autoreset", TfToken::Immortal),
      mjcFlagClampctrl("mjc:flag:clampctrl", TfToken::Immortal),
      mjcFlagConstraint("mjc:flag:constraint", TfToken::Immortal),
      mjcFlagContact("mjc:flag:contact", TfToken::Immortal),
      mjcFlagEnergy("mjc:flag:energy", TfToken::Immortal),
      mjcFlagEquality("mjc:flag:equality", TfToken::Immortal),
      mjcFlagEulerdamp("mjc:flag:eulerdamp", TfToken::Immortal),
      mjcFlagFilterparent("mjc:flag:filterparent", TfToken::Immortal),
      mjcFlagFrictionloss("mjc:flag:frictionloss", TfToken::Immortal),
      mjcFlagFwdinv("mjc:flag:fwdinv", TfToken::Immortal),
      mjcFlagGravity("mjc:flag:gravity", TfToken::Immortal),
      mjcFlagInvdiscrete("mjc:flag:invdiscrete", TfToken::Immortal),
      mjcFlagIsland("mjc:flag:island", TfToken::Immortal),
      mjcFlagLimit("mjc:flag:limit", TfToken::Immortal),
      mjcFlagMidphase("mjc:flag:midphase", TfToken::Immortal),
      mjcFlagMulticcd("mjc:flag:multiccd", TfToken::Immortal),
      mjcFlagNativeccd("mjc:flag:nativeccd", TfToken::Immortal),
      mjcFlagOverride("mjc:flag:override", TfToken::Immortal),
      mjcFlagPassive("mjc:flag:passive", TfToken::Immortal),
      mjcFlagRefsafe("mjc:flag:refsafe", TfToken::Immortal),
      mjcFlagSensor("mjc:flag:sensor", TfToken::Immortal),
      mjcFlagWarmstart("mjc:flag:warmstart", TfToken::Immortal),
      mjcForceLimited("mjc:forceLimited", TfToken::Immortal),
      mjcForceRangeMax("mjc:forceRange:max", TfToken::Immortal),
      mjcForceRangeMin("mjc:forceRange:min", TfToken::Immortal),
      mjcGainPrm("mjc:gainPrm", TfToken::Immortal),
      mjcGainType("mjc:gainType", TfToken::Immortal),
      mjcGear("mjc:gear", TfToken::Immortal),
      mjcInertia("mjc:inertia", TfToken::Immortal),
      mjcJointInParent("mjc:jointInParent", TfToken::Immortal),
      mjcLengthRangeMax("mjc:lengthRange:max", TfToken::Immortal),
      mjcLengthRangeMin("mjc:lengthRange:min", TfToken::Immortal),
      mjcOptionActuatorgroupdisable("mjc:option:actuatorgroupdisable",
                                    TfToken::Immortal),
      mjcOptionApirate("mjc:option:apirate", TfToken::Immortal),
      mjcOptionCcd_iterations("mjc:option:ccd_iterations", TfToken::Immortal),
      mjcOptionCcd_tolerance("mjc:option:ccd_tolerance", TfToken::Immortal),
      mjcOptionCone("mjc:option:cone", TfToken::Immortal),
      mjcOptionDensity("mjc:option:density", TfToken::Immortal),
      mjcOptionImpratio("mjc:option:impratio", TfToken::Immortal),
      mjcOptionIntegrator("mjc:option:integrator", TfToken::Immortal),
      mjcOptionIterations("mjc:option:iterations", TfToken::Immortal),
      mjcOptionJacobian("mjc:option:jacobian", TfToken::Immortal),
      mjcOptionLs_iterations("mjc:option:ls_iterations", TfToken::Immortal),
      mjcOptionLs_tolerance("mjc:option:ls_tolerance", TfToken::Immortal),
      mjcOptionMagnetic("mjc:option:magnetic", TfToken::Immortal),
      mjcOptionNoslip_iterations("mjc:option:noslip_iterations",
                                 TfToken::Immortal),
      mjcOptionNoslip_tolerance("mjc:option:noslip_tolerance",
                                TfToken::Immortal),
      mjcOptionO_friction("mjc:option:o_friction", TfToken::Immortal),
      mjcOptionO_margin("mjc:option:o_margin", TfToken::Immortal),
      mjcOptionO_solimp("mjc:option:o_solimp", TfToken::Immortal),
      mjcOptionO_solref("mjc:option:o_solref", TfToken::Immortal),
      mjcOptionSdf_initpoints("mjc:option:sdf_initpoints", TfToken::Immortal),
      mjcOptionSdf_iterations("mjc:option:sdf_iterations", TfToken::Immortal),
      mjcOptionSolver("mjc:option:solver", TfToken::Immortal),
      mjcOptionTimestep("mjc:option:timestep", TfToken::Immortal),
      mjcOptionTolerance("mjc:option:tolerance", TfToken::Immortal),
      mjcOptionViscosity("mjc:option:viscosity", TfToken::Immortal),
      mjcOptionWind("mjc:option:wind", TfToken::Immortal),
      mjcRefSite("mjc:refSite", TfToken::Immortal),
      mjcShellinertia("mjc:shellinertia", TfToken::Immortal),
      mjcSliderSite("mjc:sliderSite", TfToken::Immortal),
      muscle("muscle", TfToken::Immortal),
      newton("newton", TfToken::Immortal),
      none("none", TfToken::Immortal),
      pgs("pgs", TfToken::Immortal),
      pyramidal("pyramidal", TfToken::Immortal),
      rk4("rk4", TfToken::Immortal),
      shell("shell", TfToken::Immortal),
      sparse("sparse", TfToken::Immortal),
      true_("true", TfToken::Immortal),
      user("user", TfToken::Immortal),
      CollisionAPI("CollisionAPI", TfToken::Immortal),
      MeshCollisionAPI("MeshCollisionAPI", TfToken::Immortal),
      PhysicsActuatorAPI("PhysicsActuatorAPI", TfToken::Immortal),
      SceneAPI("SceneAPI", TfToken::Immortal),
      SiteAPI("SiteAPI", TfToken::Immortal),
      allTokens({affine,
                 auto_,
                 cg,
                 convex,
                 dense,
                 elliptic,
                 euler,
                 exact,
                 false_,
                 filter,
                 filterexact,
                 fixed,
                 implicit,
                 implicitfast,
                 integrator,
                 legacy,
                 mjcActDim,
                 mjcActEarly,
                 mjcActLimited,
                 mjcActRangeMax,
                 mjcActRangeMin,
                 mjcBiasPrm,
                 mjcBiasType,
                 mjcCrankLength,
                 mjcCrankSite,
                 mjcCtrlLimited,
                 mjcCtrlRangeMax,
                 mjcCtrlRangeMin,
                 mjcDynPrm,
                 mjcDynType,
                 mjcFlagActuation,
                 mjcFlagAutoreset,
                 mjcFlagClampctrl,
                 mjcFlagConstraint,
                 mjcFlagContact,
                 mjcFlagEnergy,
                 mjcFlagEquality,
                 mjcFlagEulerdamp,
                 mjcFlagFilterparent,
                 mjcFlagFrictionloss,
                 mjcFlagFwdinv,
                 mjcFlagGravity,
                 mjcFlagInvdiscrete,
                 mjcFlagIsland,
                 mjcFlagLimit,
                 mjcFlagMidphase,
                 mjcFlagMulticcd,
                 mjcFlagNativeccd,
                 mjcFlagOverride,
                 mjcFlagPassive,
                 mjcFlagRefsafe,
                 mjcFlagSensor,
                 mjcFlagWarmstart,
                 mjcForceLimited,
                 mjcForceRangeMax,
                 mjcForceRangeMin,
                 mjcGainPrm,
                 mjcGainType,
                 mjcGear,
                 mjcInertia,
                 mjcJointInParent,
                 mjcLengthRangeMax,
                 mjcLengthRangeMin,
                 mjcOptionActuatorgroupdisable,
                 mjcOptionApirate,
                 mjcOptionCcd_iterations,
                 mjcOptionCcd_tolerance,
                 mjcOptionCone,
                 mjcOptionDensity,
                 mjcOptionImpratio,
                 mjcOptionIntegrator,
                 mjcOptionIterations,
                 mjcOptionJacobian,
                 mjcOptionLs_iterations,
                 mjcOptionLs_tolerance,
                 mjcOptionMagnetic,
                 mjcOptionNoslip_iterations,
                 mjcOptionNoslip_tolerance,
                 mjcOptionO_friction,
                 mjcOptionO_margin,
                 mjcOptionO_solimp,
                 mjcOptionO_solref,
                 mjcOptionSdf_initpoints,
                 mjcOptionSdf_iterations,
                 mjcOptionSolver,
                 mjcOptionTimestep,
                 mjcOptionTolerance,
                 mjcOptionViscosity,
                 mjcOptionWind,
                 mjcRefSite,
                 mjcShellinertia,
                 mjcSliderSite,
                 muscle,
                 newton,
                 none,
                 pgs,
                 pyramidal,
                 rk4,
                 shell,
                 sparse,
                 true_,
                 user,
                 CollisionAPI,
                 MeshCollisionAPI,
                 PhysicsActuatorAPI,
                 SceneAPI,
                 SiteAPI}) {}

TfStaticData<MjcPhysicsTokensType> MjcPhysicsTokens;

PXR_NAMESPACE_CLOSE_SCOPE
