# Description:
#   Tests for mujoco/plugin/decoder

load("@rules_cc//cc:cc_test.bzl", "cc_test")
load("//:build_defs.bzl", "MJ_ROOT")

licenses(["notice"])

cc_test(
    name = "decoder_test",
    srcs = ["decoder_test.cc"],
    conlyopts = ["-std=c11"],
    copts = [
        "-I" + MJ_ROOT,
        "-I" + MJ_ROOT + "/include",
        "-I" + MJ_ROOT + "/src",
    ],
    cxxopts = ["-std=c++20"],
    data = ["//test/user/testdata:test_mjcf"],
    deps = [
        "//:libmujoco_hdrs",
        "//plugin/gmsh_decoder",
        "//test:fixture",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)
