load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("//:build_defs.bzl", "MJ_ROOT")

licenses(["notice"])

exports_files([
    ".clang-format",
    "mjcf.schema",
    "generated/.clang-format",
    "generated/dmcontrol_schema.xml",
    "generated/mjcf.xsd",
    "generated/mjcf_default_table.inc",
    "generated/mjcf_map.h",
    "generated/mjcf_read_table.inc",
    "generated/mjcf_table.inc",
    "xml_native_reader.cc",
    "xml_native_writer.cc",
])

cc_library(
    name = "xml",
    srcs = ["xml.cc"],
    hdrs = ["xml.h"],
    conlyopts = ["-std=c11"],
    copts = [
        "-I" + MJ_ROOT + "/include",
        "-I" + MJ_ROOT + "/src",
        "-fexceptions",
    ],
    cxxopts = ["-std=c++20"],
    local_defines = [
        "MUJOCO_DLL_EXPORTS",
        "_GNU_SOURCE",
    ],
    visibility = [
        "//src:__subpackages__",
    ],
    deps = [
        ":xml_native_reader",
        ":xml_native_writer",
        ":xml_urdf",
        ":xml_util",
        "//:libmujoco_hdrs",
        "//src/cc:array_safety",
        "//src/engine:engine_crossplatform",
        "//src/user:user_resource",
        "//src/user:user_util",
        "//src/user:user_vfs",
        "@tinyxml2",
    ],
)

cc_library(
    name = "xml_api",
    srcs = ["xml_api.cc"],
    hdrs = ["xml_api.h"],
    conlyopts = ["-std=c11"],
    copts = [
        "-I" + MJ_ROOT + "/include",
        "-I" + MJ_ROOT + "/src",
    ],
    cxxopts = ["-std=c++20"],
    local_defines = [
        "MUJOCO_DLL_EXPORTS",
        "_GNU_SOURCE",
    ],
    visibility = [
        "//:__subpackages__",
    ],
    deps = [
        ":xml",
        ":xml_global",
        ":xml_native_reader",
        ":xml_util",
        "//:libmujoco_hdrs",
        "//src/engine:engine_io",
        "//src/user:user_resource",
        "//src/user:user_vfs",
    ],
)

cc_library(
    name = "xml_base",
    srcs = ["xml_base.cc"],
    hdrs = [
        "generated/mjcf_map.h",  # buildcleaner: keep
        "xml_base.h",
    ],
    conlyopts = ["-std=c11"],
    copts = [
        "-I" + MJ_ROOT + "/include",
        "-I" + MJ_ROOT + "/src",
        "-fexceptions",
    ],
    cxxopts = ["-std=c++20"],
    local_defines = [
        "MUJOCO_DLL_EXPORTS",
        "_GNU_SOURCE",
    ],
    deps = [
        ":xml_util",
        "//:libmujoco_hdrs",
        "//src/user:user_composite",
        "//src/user:user_model",
        "@tinyxml2",
    ],
)

cc_library(
    name = "xml_global",
    srcs = ["xml_global.cc"],
    hdrs = ["xml_global.h"],
    conlyopts = ["-std=c11"],
    copts = [
        "-I" + MJ_ROOT + "/include",
        "-I" + MJ_ROOT + "/src",
        "-fexceptions",
    ],
    cxxopts = ["-std=c++20"],
    local_defines = [
        "MUJOCO_DLL_EXPORTS",
        "_GNU_SOURCE",
    ],
    visibility = ["//:__subpackages__"],
    deps = [
        ":xml",
        ":xml_util",
        "//:libmujoco_hdrs",
    ],
)

cc_library(
    name = "xml_native_reader",
    srcs = [
        "generated/mjcf_read_table.inc",  # buildcleaner: keep
        "generated/mjcf_table.inc",  # buildcleaner: keep
        "xml_native_reader.cc",
    ],
    hdrs = ["xml_native_reader.h"],
    conlyopts = ["-std=c11"],
    copts = [
        "-I" + MJ_ROOT + "/include",
        "-I" + MJ_ROOT + "/src",
        "-fexceptions",
    ],
    cxxopts = ["-std=c++20"],
    local_defines = [
        "MUJOCO_DLL_EXPORTS",
        "_GNU_SOURCE",
    ],
    visibility = ["//:__subpackages__"],
    deps = [
        ":xml_base",
        ":xml_util",
        "//:libmujoco_hdrs",
        "//src/engine:engine_util_misc",
        "//src/user:user_composite",
        "//src/user:user_model",
        "//src/user:user_util",
        "@tinyxml2",
    ],
)

cc_library(
    name = "xml_native_writer",
    srcs = [
        "generated/mjcf_read_table.inc",  # buildcleaner: keep
        "xml_native_writer.cc",
    ],
    hdrs = ["xml_native_writer.h"],
    conlyopts = ["-std=c11"],
    copts = [
        "-I" + MJ_ROOT + "/include",
        "-I" + MJ_ROOT + "/src",
        "-fexceptions",
    ],
    cxxopts = ["-std=c++20"],
    local_defines = [
        "MUJOCO_DLL_EXPORTS",
        "_GNU_SOURCE",
    ],
    deps = [
        ":xml_base",
        ":xml_numeric_format",
        ":xml_util",
        "//:libmujoco_hdrs",
        "//src/engine:engine_io",
        "//src/engine:engine_plugin",
        "//src/engine:engine_support",
        "//src/engine:engine_util_errmem",
        "//src/engine:engine_util_misc",
        "//src/user:user_model",
        "//src/user:user_util",
        "@tinyxml2",
    ],
)

cc_library(
    name = "xml_urdf",
    srcs = ["xml_urdf.cc"],
    hdrs = ["xml_urdf.h"],
    conlyopts = ["-std=c11"],
    copts = [
        "-I" + MJ_ROOT + "/include",
        "-I" + MJ_ROOT + "/src",
        "-fexceptions",
    ],
    cxxopts = ["-std=c++20"],
    local_defines = [
        "MUJOCO_DLL_EXPORTS",
        "_GNU_SOURCE",
    ],
    visibility = ["//src:__subpackages__"],
    deps = [
        ":xml_base",
        ":xml_native_reader",
        ":xml_util",
        "//:libmujoco_hdrs",
        "//src/user:user_model",
        "//src/user:user_util",
        "@tinyxml2",
    ],
)

cc_library(
    name = "xml_util",
    srcs = ["xml_util.cc"],
    hdrs = ["xml_util.h"],
    conlyopts = ["-std=c11"],
    copts = [
        "-I" + MJ_ROOT + "/include",
        "-I" + MJ_ROOT + "/src",
        "-fexceptions",
    ],
    cxxopts = ["-std=c++20"],
    local_defines = [
        "MUJOCO_DLL_EXPORTS",
        "_GNU_SOURCE",
    ],
    visibility = ["//visibility:private"],
    deps = [
        ":xml_numeric_format",
        "//:libmujoco_hdrs",
        "//src/cc:array_safety",
        "//src/engine:engine_util_errmem",
        "//src/user:user_resource",
        "//src/user:user_util",
        "@tinyxml2",
    ],
)

cc_library(
    name = "xml_numeric_format",
    srcs = ["xml_numeric_format.cc"],
    hdrs = ["xml_numeric_format.h"],
    conlyopts = ["-std=c11"],
    copts = [
        "-I" + MJ_ROOT + "/include",
        "-I" + MJ_ROOT + "/src",
    ],
    cxxopts = ["-std=c++20"],
    local_defines = [
        "MUJOCO_DLL_EXPORTS",
        "_GNU_SOURCE",
    ],
    visibility = [
        "//test/user:__pkg__",
        "//test/xml:__subpackages__",
    ],
    deps = ["//:libmujoco_hdrs"],
)
