# Description:
#   Sample applications shipped with MuJoCo.

load("@mujoco//:build_defs.bzl", "mujoco_ui_binary")
load("@rules_cc//cc:cc_binary.bzl", "cc_binary")

licenses(["notice"])

package(default_visibility = ["@mujoco//test:__subpackages__"])

exports_files([".clang-format"])

mujoco_ui_binary(
    name = "basic",
    srcs = ["basic.cc"],
    conlyopts = ["-std=c11"],
    cxxopts = ["-std=c++20"],
    deps = [
        "@glfw",
        "@mujoco",
        "@mujoco//:graphics_native",  # buildcleaner: keep
        "@mujoco//plugin/actuator:register",
        "@mujoco//plugin/elasticity:register",
        "@mujoco//plugin/sdf:register",
        "@mujoco//plugin/sensor:register",
    ],
)

cc_binary(
    name = "compile",
    srcs = ["compile.cc"],
    conlyopts = ["-std=c11"],
    cxxopts = ["-std=c++20"],
    visibility = [
        "@mujoco//test/sample:__subpackages__",
    ],
    deps = [
        "@mujoco",
        "@mujoco//plugin/actuator:register",
        "@mujoco//plugin/elasticity:register",
        "@mujoco//plugin/sdf:register",
        "@mujoco//plugin/sensor:register",
    ],
)

cc_binary(
    name = "dependencies",
    srcs = ["dependencies.cc"],
    conlyopts = ["-std=c11"],
    cxxopts = ["-std=c++20"],
    deps = [
        "@mujoco",
    ],
)

cc_binary(
    name = "record",
    srcs = [
        "array_safety.h",
        "record.cc",
    ],
    conlyopts = ["-std=c11"],
    cxxopts = ["-std=c++20"],
    deps = [
        "@glfw",
        "@mujoco",
        "@mujoco//:graphics_native",  # buildcleaner: keep
        "@mujoco//plugin/actuator:register",
        "@mujoco//plugin/elasticity:register",
        "@mujoco//plugin/sdf:register",
        "@mujoco//plugin/sensor:register",
        "@mujoco//src/cc:array_safety",
    ],
)

cc_binary(
    name = "testspeed",
    srcs = ["testspeed.cc"],
    conlyopts = ["-std=c11"],
    cxxopts = ["-std=c++20"],
    deps = [
        "@mujoco",
        "@mujoco//plugin/actuator:register",
        "@mujoco//plugin/elasticity:register",
        "@mujoco//plugin/sdf:register",
        "@mujoco//plugin/sensor:register",
    ],
)
