# Description:
#   Tests for mujoco/plugin/elasticity

load("@rules_cc//cc:cc_test.bzl", "cc_test")
load("//:build_defs.bzl", "MJ_ROOT")

licenses(["notice"])

cc_test(
    name = "elasticity_test",
    srcs = ["elasticity_test.cc"],
    conlyopts = ["-std=c11"],
    copts = [
        "-I" + MJ_ROOT,
        "-I" + MJ_ROOT + "/include",
        "-I" + MJ_ROOT + "/src",
    ],
    cxxopts = ["-std=c++20"],
    deps = [
        "//:libmujoco_hdrs",
        "//plugin/elasticity:register",
        "//test:fixture",
        "@googletest//:gtest_main",
    ],
)
