load("@rules_cc//cc:cc_binary.bzl", "cc_binary")
load("@rules_cc//cc:cc_library.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

_CXXOPTS = select({
    "@platforms//os:windows": ["/std:c++20"],
    "//conditions:default": ["-std=c++20"],
})

cc_library(
    name = "sdf_static",
    srcs = [
        "bolt.cc",
        "bowl.cc",
        "gear.cc",
        "nut.cc",
        "register.cc",
        "sdf.cc",
        "torus.cc",
    ],
    hdrs = [
        "bolt.h",
        "bowl.h",
        "gear.h",
        "nut.h",
        "sdf.h",
        "torus.h",
    ],
    copts = _CXXOPTS,
    deps = ["//:mujoco"],
    alwayslink = True,
)

cc_binary(
    name = "libsdf_plugin.so",
    srcs = [
        "bolt.cc",
        "bolt.h",
        "bowl.cc",
        "bowl.h",
        "gear.cc",
        "gear.h",
        "nut.cc",
        "nut.h",
        "register.cc",
        "sdf.cc",
        "sdf.h",
        "torus.cc",
        "torus.h",
    ],
    copts = _CXXOPTS,
    linkshared = True,
    target_compatible_with = ["@platforms//os:linux"],
    deps = ["//:mujoco_shared"],
)

cc_binary(
    name = "libsdf_plugin.dylib",
    srcs = [
        "bolt.cc",
        "bolt.h",
        "bowl.cc",
        "bowl.h",
        "gear.cc",
        "gear.h",
        "nut.cc",
        "nut.h",
        "register.cc",
        "sdf.cc",
        "sdf.h",
        "torus.cc",
        "torus.h",
    ],
    copts = _CXXOPTS,
    linkshared = True,
    target_compatible_with = ["@platforms//os:macos"],
    deps = ["//:mujoco_shared"],
)

cc_binary(
    name = "sdf_plugin.dll",
    srcs = [
        "bolt.cc",
        "bolt.h",
        "bowl.cc",
        "bowl.h",
        "gear.cc",
        "gear.h",
        "nut.cc",
        "nut.h",
        "register.cc",
        "sdf.cc",
        "sdf.h",
        "torus.cc",
        "torus.h",
    ],
    copts = _CXXOPTS,
    linkshared = True,
    target_compatible_with = ["@platforms//os:windows"],
    deps = ["//:mujoco_shared"],
)

alias(
    name = "shared",
    actual = select({
        "@platforms//os:linux": ":libsdf_plugin.so",
        "@platforms//os:macos": ":libsdf_plugin.dylib",
        "@platforms//os:windows": ":sdf_plugin.dll",
    }),
)

alias(
    name = "sdf",
    actual = ":sdf_static",
)
