# Description:
#   Tests for mujoco/plugin/sensor

load("@rules_cc//cc:cc_test.bzl", "cc_test")
load("//:build_defs.bzl", "MJ_ROOT")

licenses(["notice"])

cc_test(
    name = "sensor_test",
    srcs = ["sensor_test.cc"],
    conlyopts = ["-std=c11"],
    copts = [
        "-I" + MJ_ROOT,
        "-I" + MJ_ROOT + "/include",
        "-I" + MJ_ROOT + "/src",
    ],
    cxxopts = ["-std=c++20"],
    data = [
        "//test/plugin/sensor/testdata:test_mjcf",
    ],
    deps = [
        "//:libmujoco_hdrs",
        "//plugin/sensor:register",
        "//test:fixture",
        "@googletest//:gtest_main",
    ],
)
